use_frameworks!

platform :ios, '8.0'

target 'DHNetworking_Example' do
  pod 'DHNetworking', :path => '../'

  target 'DHNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
